param(
    [string]$GameRoot = '',
    [switch]$SkipDecompile,
    [switch]$SkipRestore
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
[Console]::OutputEncoding = [Text.Encoding]::UTF8

$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$defaultGameRoot = 'C:\Program Files (x86)\Steam\steamapps\common\The Scroll Of Taiwu'
if ([string]::IsNullOrWhiteSpace($GameRoot)) { $GameRoot = $env:TAIWU_GAME_DIR }
if ([string]::IsNullOrWhiteSpace($GameRoot)) { $GameRoot = $defaultGameRoot }
$GameRoot = [IO.Path]::GetFullPath($GameRoot).TrimEnd('\')
$SteamApps = Split-Path -Parent (Split-Path -Parent $GameRoot)
$DecompiledRoot = if (-not [string]::IsNullOrWhiteSpace($env:JHYL_DECOMPILED_ROOT)) {
    [IO.Path]::GetFullPath($env:JHYL_DECOMPILED_ROOT).TrimEnd('\')
} else {
    Join-Path $Root '.decompiled'
}
$manifest = Join-Path $SteamApps 'appmanifest_838350.acf'
$managed = Join-Path $GameRoot 'The Scroll of Taiwu_Data\Managed'
$backend = Join-Path $GameRoot 'Backend'

foreach ($required in @($manifest, (Join-Path $managed 'Assembly-CSharp.dll'), (Join-Path $backend 'GameData.dll'))) {
    if (-not (Test-Path -LiteralPath $required -PathType Leaf)) {
        throw "Missing Taiwu development dependency: $required`nUse -GameRoot to select the Taiwu installation directory."
    }
}

$escapedGameRoot = [Security.SecurityElement]::Escape($GameRoot)
$localProps = [string]::Join("`n", @(
    '<Project>',
    '  <!-- Generated by tools/bootstrap-development.ps1; machine-local and ignored by Git. -->',
    '  <PropertyGroup>',
    "    <TaiwuGameDir>$escapedGameRoot</TaiwuGameDir>",
    '  </PropertyGroup>',
    '</Project>'
))
$utf8 = New-Object Text.UTF8Encoding($false)
[IO.File]::WriteAllText((Join-Path $Root 'Directory.Build.local.props'), $localProps.Trim() + "`n", $utf8)
Write-Host "[OK] Configured local Taiwu path: $GameRoot"

$dotnet = (Get-Command dotnet -ErrorAction Stop).Source
if (-not $SkipDecompile) {
    $buildMatch = Select-String -LiteralPath $manifest -Pattern '"buildid"\s+"([0-9]+)"' | Select-Object -First 1
    if (-not $buildMatch) { throw "Cannot read Steam buildid: $manifest" }
    $buildId = [regex]::Match($buildMatch.Line, '"buildid"\s+"([0-9]+)"').Groups[1].Value
    $snapshot = Join-Path $DecompiledRoot "taiwu_decomp_b$buildId"
    if (Test-Path -LiteralPath (Join-Path $snapshot '_COMPLETE') -PathType Leaf) {
        Write-Host "[OK] Current decompiled authority already exists: $snapshot"
    } else {
        $ilspy = Join-Path $env:USERPROFILE '.dotnet\tools\ilspycmd.exe'
        if (-not (Test-Path -LiteralPath $ilspy -PathType Leaf)) {
            & $dotnet tool install --global ilspycmd --version 8.2.0.7535
            if ($LASTEXITCODE -ne 0) { throw 'Failed to install ilspycmd 8.2.0.7535' }
        }
        $oldRollForward = $env:DOTNET_ROLL_FORWARD
        try {
            $env:DOTNET_ROLL_FORWARD = 'LatestMajor'
            & (Join-Path $Root 'tools\decompile-latest.ps1') -GameRoot $GameRoot
        } finally {
            $env:DOTNET_ROLL_FORWARD = $oldRollForward
        }
    }
}

if (-not $SkipRestore) {
    $projects = @(Get-ChildItem -LiteralPath (Join-Path $Root 'src'), (Join-Path $Root 'tools') -Filter '*.csproj' -File -Recurse)
    foreach ($project in $projects) {
        & $dotnet restore $project.FullName --nologo
        if ($LASTEXITCODE -ne 0) { throw "NuGet restore failed: $($project.FullName)" }
    }
    Write-Host "[OK] Restored $($projects.Count) projects"
}

Write-Host ''
Write-Host 'Development environment is ready. Recommended next command:'
Write-Host '  powershell.exe -NoProfile -ExecutionPolicy Bypass -File tools\full-mod-e2e.ps1'
Write-Host 'Read docs\development.md before running tests or deploying a Release build.'
